import {initial,seed,therapists,scenarios,startBatch,unresolved,suggestion,decide,reopen,commit,abandon,removeRoom,addStaff,removeStaff,setStaffHours,addClient,removeClient,workableOptions,conflictsFor,saveManual,addStanding,refreshDraft,editCalendarSession,draftCalendar} from './model.mjs';
let state=initial(),page='schedule',selected='s1',scenario='simple',error='',notice='',week=0,pendingSetup=null,pendingDraft=false,calendarSelection=null,calendarNewDate=null,reportStaff=therapists[0],reportMonth='2026-10';
const $=s=>document.querySelector(s);
const e=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,action,cls='',value='')=>`<button type="button" class="${cls}" data-action="${action}" data-value="${e(value)}">${label}</button>`;
const tag=(text,cls='')=>`<span class="tag ${cls}">${e(text)}</span>`;
const place=s=>s.location==='Home'?'Home':`Room ${s.room}`;
const batch=()=>state.batch;
const conflictAlert=(where='')=>{
 const count=unresolved(state);
 return `<button type="button" class="conflict-alert ${count?'has-conflicts':'no-conflicts'} ${where}" data-action="calendar-conflicts" aria-label="${count?`${count} Schedule conflicts`:'No conflicts'}. Open Calendar.">${count?'⚠':''}<strong>${count}</strong><span>${count?'Schedule conflicts':'No conflicts'}</span></button>`;
};
function calendarStyle(s,sessions=state.schedule){
 const minute=x=>Number(x.time.slice(0,2))*60+Number(x.time.slice(3));
 const peers=sessions.filter(x=>x.date===s.date && minute(x)<minute(s)+s.minutes && minute(s)<minute(x)+x.minutes).sort((a,b)=>a.id.localeCompare(b.id));
 return `top:${(minute(s)-540)*2}px;min-height:${Math.max(100,s.minutes*2)}px;width:calc(${100/peers.length}% - 4px);left:calc(${peers.findIndex(x=>x.id===s.id)*100/peers.length}% + 2px)`;
}
const steps=current=>`<div class="steps">${['Report leave','Review issues','Preview & commit','Notifications'].map((s,i)=>`<span class="${i===current?'current':''}">${i+1} · ${s}</span>`).join('')}</div>`;
const header=(title,sub,actions='')=>`<div class="top"><div><div class="eyebrow">Maple pod / Clinic workspace</div><h1>${title}</h1><p class="muted">${sub}</p></div><div class="actions">${actions}</div></div>`;
const assumptions=()=>`<details><summary>Prototype notes & open decisions</summary><div class="assumptions"><p>This is a scripted experience. Buttons change temporary sample data only. Reload or Reset walkthrough restores the starting state. No real schedule or room data is changed.</p><p>Q-001/008: sample dates and office/week boundaries are illustrative. Q-004/005/009: one draft batch is shown; leave editing and abandoned-leave persistence remain undecided. Q-002/003/006/007: sample time boundaries and cascade ordering remain illustrative. Manual changes may create draft issues, but all outstanding issues must be resolved before commit (approved D-B005). Q-015: weekly setup creates only the first sample occurrence.</p><p>Approved rules: 15 configurable shared rooms, no double booking, no room for home visits, full admin-booked duration, explicit decisions and commit. Room conflicts across pods are shown without other clients’ details.</p></div></details>`;
function oldScheduleScreen(){
 const rows=state.schedule.filter(s=>week===0?s.date<'2026-09-21':s.date>='2026-09-21');
 return header('Your clinic, at a glance','See the schedule before deciding what needs to change.',btn(state.batch?'Open Calendar':'Report leave',state.batch?'schedule':'leave','primary'))+
 `<div class="cards"><div class="card"><div class="muted">Sessions this week</div><div class="metric">${rows.filter(s=>s.status!=='Cancelled').length}</div><span class="muted">Clinic and home visits</span></div><div class="card"><div class="muted">Needs attention</div><div class="metric">${unresolved(state)} <small>unresolved</small></div><span class="muted">${batch()?'Draft changes have not been committed':'No active disruption batch'}</span></div><div class="card"><div class="muted">Shared clinic rooms</div><div class="metric">${state.rooms.length}</div><span class="muted">Available inventory across all pods</span></div></div>`+
 `<section class="panel"><div class="top"><h2>Committed sample schedule</h2>${tag('Draft decisions do not change this view','gray')}</div><div class="week">${btn('Sep 14 – 20','week',week===0?'primary':'','0')}${btn('Sep 21 – 27','week',week===1?'primary':'','1')}</div><div class="scroll"><table><thead><tr><th>Client / Date</th><th>Time</th><th>Therapist</th><th>Location</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(s=>`<tr><td><strong>${e(s.client)}</strong><br><span class="muted">${s.date}</span></td><td>${s.time}<br><span class="muted">${s.minutes} min</span></td><td>${e(s.therapist)}</td><td>${tag(place(s),s.location==='Home'?'gray':'')}</td><td>${tag(s.status,s.status==='Cancelled'?'amber':'')}</td><td>${btn('Details','details','',s.id)}</td></tr>`).join('')}</tbody></table></div></section>`+assumptions();
}
function scheduleScreen(){
 if(batch())return editCalendarScreen();
 const start=week===0?14:21,dates=Array.from({length:5},(_,i)=>`2026-09-${start+i}`),days=['Monday','Tuesday','Wednesday','Thursday','Friday'];
 return header('The weekly clinic calendar','Plan normal sessions and respond to disruptions in one workspace.',btn('Add session','calendar-add','primary')+btn('Report leave','leave'))+
 `<div class="week">${btn('Sep 14 – 18','week',week===0?'primary':'','0')}${btn('Sep 21 – 25','week',week===1?'primary':'','1')}${tag('Committed sample schedule','gray')}</div><div class="calendar-scroll"><div class="calendar"><div class="time-column"><div class="day-title">Time</div>${Array.from({length:9},(_,i)=>`<div class="hour-label">${String(9+i).padStart(2,'0')}:00</div>`).join('')}</div>${dates.map((date,i)=>`<div class="day-column"><div class="day-title"><strong>${days[i]}</strong><br>Sep ${start+i}</div><div class="day-grid">${state.schedule.filter(s=>s.date===date).map(s=>`<button class="calendar-event ${s.location==='Home'?'home':''} ${s.status==='Cancelled'?'cancelled':''}" style="${calendarStyle(s)}" data-action="details" data-value="${s.id}"><strong>${e(s.client)}</strong><span>${s.time} · ${s.minutes} min</span><span>${e(s.therapist)}</span><span>${place(s)}${s.status==='Cancelled'?' · Cancelled':''}</span></button>`).join('')}</div></div>`).join('')}</div></div><p class="notes">Home visits use the complete booked duration. Sessions are weekly templates with supplied sample occurrences; this is not a recurrence engine. Overlapping columns in this all-therapist view represent different therapists.</p>`+assumptions();
}
function editCalendarScreen(){
 if(!batch())return header('No active draft','Report leave first to explore calendar conflict handling.',btn('Report leave','leave','primary'));
 const outstanding=refreshDraft(state),sessions=draftCalendar(state),start=week===0?14:21;
 const dates=Array.from({length:7},(_,i)=>`2026-09-${start+i}`),days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
 const current=calendarSelection==='new'?{id:`draft-add-${batch().issues.length+1}`,client:'Alex Demo',therapist:therapists[0],date:calendarNewDate||`2026-09-${start}`,time:'09:00',minutes:60,location:'Clinic',room:1,status:'Scheduled'}:sessions.find(s=>s.id===calendarSelection);
 const grid=`<div class="calendar-scroll"><div class="calendar editable-grid"><div class="time-column"><div class="day-title">Time</div>${Array.from({length:9},(_,i)=>`<div class="hour-label">${9+i}:00</div>`).join('')}</div>${dates.map((date,i)=>`<div class="day-column"><div class="day-title"><strong>${days[i]} · Sep ${start+i}</strong><br>${btn('+ Session','calendar-add-day','',date)}</div><div class="day-grid">${sessions.filter(s=>s.date===date).map(s=>`<button class="calendar-event ${s.id===calendarSelection?'selected-event':''} ${s.location==='Home'?'home':''} ${s.status==='Cancelled'?'cancelled':''} ${outstanding.some(i=>i.id===s.id)?'conflict-event':''}" style="${calendarStyle(s,sessions)}" data-action="calendar-select" data-value="${s.id}"><strong>${e(s.client)}</strong><span>${s.time} · ${s.minutes} min</span><span>${e(s.therapist)}</span><span>${place(s)}${s.status==='Cancelled'?' · Cancelled':''}</span>${outstanding.some(i=>i.id===s.id)?'<span>⚠ Needs attention</span>':''}</button>`).join('')}</div></div>`).join('')}</div></div>`;
 const list=`<section class="live-conflicts" aria-label="Live conflict list"><h2>Needs attention · ${outstanding.length}</h2><p class="muted">Updates after every saved edit. Click a conflict to see suggestions, or edit a session directly on the calendar.</p><div aria-live="polite">${outstanding.length?outstanding.map(i=>`<button class="conflict-item" data-action="conflict-suggestions" data-value="${i.id}"><strong>${e(i.original.client)}</strong><span>${(i.decision||i.original).date} · ${(i.decision||i.original).time}</span>${(i.conflicts.length?i.conflicts:['Decision still needed for this affected session.']).map(c=>`<small>${e(c)}</small>`).join('')}</button>`).join(''):'<div class="notice">All clear. You can preview and commit.</div>'}</div></section>`;
 const editor=current&&calendarSelection!=='new'?`<section class="calendar-inspector"><h2>Edit session</h2><p><strong>${e(current.client)}</strong></p><form id="calendar-form" data-session="${current.id}">${fields(current).replace('First occurrence (repeats weekly)','Date')}<p class="muted">Save freely into the draft. New conflicts appear above; they must be resolved before commit.</p><div class="actions"><button type="submit" class="primary">Save to draft</button>${current.status!=='Cancelled'?btn('Cancel session','calendar-cancel','danger',current.id):''}</div></form></section>`:'<section class="calendar-inspector"><h2>Add or edit in the calendar</h2><p>Choose a session to move or cancel it, or use Add session. Suggestions are optional.</p></section>';
 return header('The weekly clinic calendar','Draft changes and conflict resolution stay in this Calendar until you commit or abandon them.',btn('Batch details','review')+btn('Add session','calendar-add','primary')+btn('Preview changes','preview'))+`<div class="week">${btn('Sep 14 – 20','week',week===0?'primary':'','0')}${btn('Sep 21 – 27','week',week===1?'primary':'','1')}${tag('Draft · not committed','amber')}<span class="muted">Committed schedule remains unchanged</span></div><div class="calendar-workspace"><div>${grid}</div><aside class="calendar-side">${list}${editor}</aside></div>`;
}
function fields(session,setup=false){
 const clients=state.clients;
 return `<div class="form-grid">${setup?`<label class="field">Client<select name="client">${clients.map(c=>`<option value="${e(c)}">Client · ${e(c)}</option>`).join('')}</select></label>`:''}<label class="field">Assigned therapist<select name="therapist">${therapists.map(t=>`<option value="${e(t)}" ${session.therapist===t?'selected':''}>Therapist · ${e(t)}</option>`).join('')}</select></label><label class="field">${setup?'First occurrence (repeats weekly)':'Date'}<input required type="date" name="date" value="${session.date}" min="2026-09-14" max="2026-09-25"></label><label class="field">Start time<input required type="time" name="time" value="${session.time}"></label><label class="field">Booked duration (minutes)<input required type="number" min="15" max="480" step="15" name="minutes" value="${session.minutes}"></label><label class="field">Location<select name="location"><option ${session.location==='Clinic'?'selected':''}>Clinic</option><option ${session.location==='Home'?'selected':''}>Home</option></select></label><label class="field">Room (ignored for Home)<select name="room">${state.rooms.map(r=>`<option value="${r}" ${session.room===r?'selected':''}>Room ${r}</option>`).join('')}</select></label></div>`;
}
function addSessionDialog(date=''){const draft=Boolean(batch()),session={id:draft?`draft-add-${batch().issues.length+1}`:`setup-${state.schedule.length+1}`,client:state.clients[0],therapist:therapists[0],date:date||'2026-09-15',time:'09:00',minutes:60,location:'Clinic',room:1,status:'Scheduled'};dialog('Add a session',`<form id="session-add-form" data-draft="${draft}">${fields(session,true)}<label class="checkline"><input type="checkbox" name="weekly" checked> Repeat weekly (sample first occurrence only)</label><p class="screen-note">Prototype only: weekly keeps this first occurrence as a standing marker; it does not create a production recurrence rule.${draft?' This remains a draft until explicit batch commit.':''}</p><div class="dialog-actions"><button class="primary" type="submit">Preview session</button></div></form>`,'');}
function showAlternatives(id){
 const options=workableOptions(state,id);
 dialog(`Suggestions for ${e(batch().issues.find(i=>i.id===id).original.client)}`,`<p>All ${options.length} workable therapist/time combinations for this sample day. Each room selector includes every free sample room.</p><p class="muted">Bounded sample: 09:00, 10:30, 12:00, 14:00, 15:30; three assigned therapists. No new conflicts. The suggested option is highlighted.</p><div class="option-list">${options.map((o,i)=>`<div class="option ${i===0?'recommended':''}"><strong>${e(o.therapist)}</strong> ${i===0?tag('Suggested'):''}<p>${o.date} · ${o.time} · ${o.minutes} min</p>${o.location==='Home'?tag('Home'):`<label>Available room <select id="option-room-${i}">${o.rooms.map(r=>`<option value="${r}" ${r===o.room?'selected':''}>Room ${r}</option>`).join('')}</select></label>`}${btn('Use this option','use-option',i===0?'primary':'',`${id}:${i}`)}</div>`).join('')||'<p>No conflict-free options in this sample. You can cancel or explore a manual change.</p>'}</div>`,btn('Continue editing calendar','close'));
}
function readFields(form,base){const f=new FormData(form);return {...base,client:f.get('client')||base.client,therapist:f.get('therapist'),date:f.get('date'),time:f.get('time'),minutes:Number(f.get('minutes')),location:f.get('location'),room:f.get('location')==='Home'?null:Number(f.get('room')),status:'Scheduled'};}
function leaveScreen(){
 if(batch()) return header('A batch is already in progress','Finish or abandon it before starting another sample batch.',btn('Open Calendar','schedule','primary'));
 const multi=scenario==='multi',none=scenario==='none';
 return header('Report therapist leave','Choose a scenario, then experience how affected sessions surface.')+steps(0)+`<div class="split"><section class="panel"><form id="leave-form"><label class="field">Walkthrough scenario<select name="scenario" id="scenario">${Object.entries(scenarios).map(([k,v])=>`<option value="${k}" ${k===scenario?'selected':''}>${e(v)}</option>`).join('')}</select></label><div class="screen-note">Scripted suggestions follow the selected scenario. Your selected therapists and dates determine which sample sessions are affected.</div><h3>Therapists on leave</h3><div class="checks">${therapists.map((t,i)=>`<label><input type="checkbox" name="therapist" value="${e(t)}" ${i===0||(multi&&i===1)?'checked':''}>${e(t)}</label>`).join('')}</div><div class="form-grid" style="margin-top:20px"><label class="field">First day<input type="date" name="start" value="${none?'2026-09-28':'2026-09-14'}" required></label><label class="field">Last day<input type="date" name="end" value="${none?'2026-09-28':multi?'2026-09-25':'2026-09-14'}" required></label></div><div class="actions"><button type="submit" class="primary">Find affected sessions</button>${btn('Back to schedule','schedule')}</div></form></section><aside class="help"><h2>What happens next</h2><ol><li>See every affected session.</li><li>Review a suggestion and its reason.</li><li>Decide each session—including any bumped session.</li><li>Preview, then explicitly commit.</li></ol><p class="muted">Nothing changes in the sample schedule until you commit. Home visits keep their longer booked duration.</p></aside></div>`+assumptions();
}
function reviewScreen(){
 if(!batch())return header('No active batch','Start with a therapist absence to review the full experience.',btn('Report leave','leave','primary'));
 const b=batch(),open=unresolved(state),done=b.issues.length-open;
 if(!b.issues.length)return header('No sessions need attention',`${b.leave.start} to ${b.leave.end} · No matching sample sessions.`)+steps(1)+`<section class="panel empty"><h2>The sample schedule is unaffected</h2><p>No session changes or notifications are needed.</p>${btn('Close this empty batch','empty-close','primary')}</section>`;
 const issue=b.issues.find(i=>i.id===selected)||b.issues[0];selected=issue.id;
 const proposed=issue.decision||suggestion(issue,state),o=issue.original;
 const details=s=>`<div class="detail-line"><strong>${e(s.therapist)}</strong></div><div class="detail-line">${s.date} · ${s.time}</div><div class="detail-line">${s.minutes} minutes · ${place(s)}</div>${s.status==='Cancelled'?tag('Cancelled','amber'):''}`;
 return header('Review the affected sessions',`${b.leave.therapists.map(e).join(', ')} · ${b.leave.start} to ${b.leave.end}`,btn('Edit freely in calendar','manual','',selected)+btn('Abandon batch','abandon','danger')+btn('Preview changes','preview','primary'))+steps(1)+
 `<div class="top"><div>${tag(`${open} unresolved`,'amber')} ${tag(`${done} decided`)} ${tag('Draft · not committed','gray')}</div><span class="muted">${e(scenarios[b.scenario])}</span></div><div class="progress"><span style="width:${done/b.issues.length*100}%"></span></div><div class="review"><div class="issue-list">${b.issues.map(i=>`<button class="issue ${i.id===selected?'selected':''}" data-action="select" data-value="${i.id}"><strong>${e(i.original.client)}</strong><small>${i.original.date} · ${i.original.time} · ${place(i.original)}</small>${i.parent?`<small>↳ Bumped by ${e(b.issues.find(p=>p.id===i.parent).original.client)}</small>`:''}${tag(i.reopened?'Reopened':i.conflicts?.length?'Conflict · needs resolution':i.decision?'Decided':'Needs decision',i.decision&&!i.conflicts?.length?'':'amber')}</button>`).join('')}</div><section class="panel"><div class="top"><h2>${e(o.client)}</h2>${tag(issue.decision?'Decision saved':'Decision required',issue.decision?'':'amber')}</div><div class="reason">${e(issue.reason)}${issue.kind==='cascade'?'<br>Taylor Maple has Quinn Demo at 09:00. Accepting adds Quinn Demo as a separate issue.':''}${issue.kind==='cap'?'<br>Taylor Maple is at the sample weekly cap. Moving Quinn Demo releases one hour; Quinn Demo needs an explicit decision.':''}</div>${issue.conflicts?.length?`<div class="manual-alert" role="alert"><strong>Outstanding conflicts</strong><br>${issue.conflicts.map(e).join('<br>')}<p>Resolve these before commit.</p></div>`:''}<div class="comparison"><div><div class="eyebrow">Original · committed</div>${details(o)}</div><div class="proposed"><div class="eyebrow">${issue.decision?'Your draft decision':'Suggested · simulated'}</div>${proposed?details(proposed):'<strong>No valid replacement</strong><p class="muted">Second and third therapists cannot take this session in this scenario. Cancellation needs your decision.</p>'}</div></div>${issue.reopened?'<div class="notice error">An earlier decision or room availability changed. Review this issue again.</div>':''}<div class="actions">${issue.decision?btn('Change decision','reopen','',issue.id):(proposed?btn('Accept suggestion','accept','primary',issue.id):'')}${!issue.decision?btn('Choose alternative','alternative','',issue.id)+btn('Cancel session','cancel','danger',issue.id):''}</div><p class="notes">Only assigned therapists can appear in these sample alternatives. A third-therapist alternative has no further cascade. Every bumped session has its own decision.</p></section></div>`+assumptions();
}
function previewScreen(){
 if(!batch())return header('No batch to preview','Start a leave report first.',btn('Report leave','leave','primary'));
 const open=unresolved(state);
 return header('Check the complete change set','Review every session before explicitly committing the sample batch.',btn('Back to Calendar','schedule'))+steps(2)+`${open?`<div class="notice error">${open} unresolved issues. Commit is blocked until every issue has a decision.</div>`:'<div class="notice">All issues have a decision. The committed sample schedule is still unchanged.</div>'}<section class="panel"><div class="scroll"><table><thead><tr><th>Client</th><th>Original</th><th>Draft outcome</th><th>Reason</th></tr></thead><tbody>${batch().issues.map(i=>`<tr><td><strong>${e(i.original.client)}</strong></td><td>${i.isNew?'New session · not in committed schedule':`${i.original.date} ${i.original.time}<br>${e(i.original.therapist)} · ${place(i.original)}`}</td><td>${i.decision?i.decision.status==='Cancelled'?tag('Cancel','amber'):`${i.decision.date} ${i.decision.time}<br>${e(i.decision.therapist)} · ${place(i.decision)}`:tag('Unresolved','amber')}</td><td>${i.isNew?'Calendar addition':i.parent?'Cascaded change':i.reason.includes('calendar')?'Calendar edit':'Therapist leave'}</td></tr>`).join('')}</tbody></table></div><label class="checkline"><input id="commit-check" type="checkbox">I reviewed all decisions and want to commit this sample batch.</label><div class="actions" style="margin-top:18px">${btn('Commit sample batch','commit','primary')}${btn('Abandon batch','abandon','danger')}</div><p class="notes">This changes prototype state only. Notification tasks will be created for affected clients and therapists; nothing is sent.</p></section>`+assumptions();
}
function notificationsScreen(){
 return header('People to notify','Track the follow-up after committing a batch. No messages are sent.',btn('View schedule','schedule'))+steps(3)+`<section class="panel">${state.notifications.length?`<div class="top"><h2>${state.notifications.filter(t=>!t.done).length} tasks remaining</h2>${tag('Informational tasks only','gray')}</div>${state.notifications.map(t=>`<div class="notification ${t.done?'done':''}"><div><strong>${e(t.recipient)}</strong><p class="muted">Session for ${e(t.client)} · ${e(t.summary)}</p></div>${btn(t.done?'Mark pending':'Mark informed','notify','',t.id)}</div>`).join('')}`:'<div class="empty"><h2>No notification tasks yet</h2><p>Commit a sample batch to see who needs to be informed.</p>'+btn('Report leave','leave','primary')+'</div>'}</section>`;
}
function setupScreen(){
 const rows=(items,type)=>items.map(item=>`<div class="setup-row"><div><strong>${e(type==='staff'?item.name:item)}</strong> ${tag(type==='staff'?'Staff':'Client','gray')}${type==='staff'?`<label>Maximum hours <input class="hours-input" data-hours="${e(item.name)}" type="number" min="1" max="80" value="${item.maxHours}"> / week ${btn('Save','save-hours','',item.name)}</label>`:''}</div>${btn(`Remove ${type}`,'remove-'+type,'',type==='staff'?item.name:item)}</div>`).join('');
 return header('Setup','Infrequent clinic configuration for this fictional prototype.')+`<p class="screen-note">Prototype management only. Staff/client rules, permissions, assignments and recurrence effects remain for production discovery. Removing a referenced person is blocked so sample sessions stay intact.</p><div class="setup-grid"><section class="panel"><div class="top"><h2>Rooms</h2>${btn('Add room','add-room','primary')}</div><p class="muted">Shared inventory across all pods. Home visits do not reserve a room.</p><div class="compact-list">${state.rooms.map(r=>{const busy=r===2||state.schedule.some(s=>s.room===r&&s.status!=='Cancelled');return `<div class="setup-row"><span>Room ${r} ${tag(busy?'Booked':'No bookings',busy?'amber':'')}</span>${btn('Remove room','remove-room','',r)}</div>`}).join('')}</div></section><section class="panel"><h2>Staff</h2><form id="staff-form" class="inline-form"><input name="name" placeholder="Staff name" required><input name="hours" type="number" min="1" max="80" value="20" aria-label="Maximum hours per week"><button class="primary">Add staff</button></form><div class="compact-list">${rows(state.staff,'staff')}</div><p class="notes">Maximum hours are display-only sample configuration; they do not change suggestions, conflict checks or scheduling rules. Session assignment stays limited to the three supplied therapist fixtures.</p></section><section class="panel"><h2>Clients</h2><form id="client-form" class="inline-form"><input name="name" placeholder="Client name" required><button class="primary">Add client</button></form><div class="compact-list">${rows(state.clients,'client')}</div></section></div>`+assumptions();
}
function reportsScreen(){const choices=state.staff.map(s=>`<option value="${e(s.name)}" ${s.name===reportStaff?'selected':''}>Staff · ${e(s.name)}</option>`).join(''),label=new Intl.DateTimeFormat('en-CA',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${reportMonth}-01T00:00:00Z`)),person=state.staff.find(s=>s.name===reportStaff)?.name||therapists[0],sessions=state.schedule.filter(s=>s.therapist===person&&s.date.startsWith(reportMonth)&&s.status!=='Cancelled').sort((a,b)=>`${a.date}T${a.time}`.localeCompare(`${b.date}T${b.time}`)),total=sessions.reduce((n,s)=>n+s.minutes,0);return header('Staff schedule report','Committed synthetic schedule only. Draft changes are excluded.',btn('Print / save PDF','print-report','primary'))+`<section class="panel report-print"><div class="report-controls"><label class="field">Staff<select id="report-staff">${choices}</select></label><label class="field">Month<input id="report-month" type="month" value="${reportMonth}" min="2026-01" max="2030-12"></label></div><p class="screen-note">The supplied synthetic schedule currently spans September 2026 only. Months outside that sample horizon remain empty; no sessions are invented.</p><h2>${e(person)} · ${label}</h2>${sessions.length?`<table><thead><tr><th>Date</th><th>Time</th><th>Duration</th><th>Location</th><th>Client</th></tr></thead><tbody>${sessions.map(s=>`<tr><td>${s.date}</td><td>${s.time}</td><td>${s.minutes} min</td><td>${place(s)}</td><td>${e(s.client)}</td></tr>`).join('')}</tbody></table><p><strong>Total scheduled: ${total} minutes</strong></p>`:`<div class="empty"><h2>No committed sessions</h2><p>No sample sessions exist for ${e(person)} in ${label}.</p></div>`}<p class="notes">Prepared from temporary committed prototype state. Sharing, delivery and report retention are outside this prototype.</p></section>`;}
function render(){
 if(batch()?.calendarMode)refreshDraft(state);
 const content=({schedule:scheduleScreen,setup:setupScreen,reports:reportsScreen,leave:leaveScreen,review:reviewScreen,preview:previewScreen,notifications:notificationsScreen}[page]||scheduleScreen)();
 $('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">Stillwell</div><div class="subbrand">CLINIC WORKSPACE · DEMO</div><nav aria-label="Main navigation">${[['schedule','Calendar'],['setup','⚙ Setup'],['leave','Report leave'],['review',`Batch review${batch()?` · ${unresolved(state)}`:''}`],['reports','Reports'],['notifications','Notifications']].map(([id,label])=>btn(label,id,page===id?'active':'')).join('')}</nav><div class="pod"><strong>Maple pod</strong>Admin workspace<br>All people are fictional${conflictAlert('bottom-alert')}</div></aside><main class="main"><div class="prototype"><span><strong>INTERACTIVE UX PROTOTYPE</strong> · Scripted outcomes, temporary sample data</span><div class="global-actions">${conflictAlert('top-alert')}${btn('Reset walkthrough','reset')}</div></div><div class="content">${error?`<div class="notice error" role="alert">${e(error)}</div>`:notice?`<div class="notice" role="status">${e(notice)}</div>`:''}${content}</div></main></div><dialog id="modal"></dialog>`;
 labelNames();
}
function labelNames(){
 const roles=[...therapists.map(n=>[n,'Therapist']),...state.clients.map(n=>[n,'Client'])];
 const walker=document.createTreeWalker($('#app'),NodeFilter.SHOW_TEXT);let node;
 while((node=walker.nextNode()))for(const [name,role] of roles){
  if(!node.textContent.includes(name))continue;
  node.textContent=node.textContent.replaceAll(name,(match,offset,text)=>/(Client|Therapist|Admin)\s*·\s*$/.test(text.slice(0,offset))?match:`${role} · ${name}`);
 }
}
function dialog(title,body,actions){const d=$('#modal');d.innerHTML=`<h2>${title}</h2>${body}<div class="dialog-actions">${btn(title.startsWith('Suggestions for')?'Close suggestions':'Back','close')}${actions}</div>`;labelNames();if(!d.open)d.showModal();}
function go(dest){page=dest;error='';notice='';render();window.scrollTo(0,0);}
document.addEventListener('change',event=>{if(event.target.id==='scenario'){scenario=event.target.value;render();}if(event.target.id==='report-staff'){reportStaff=event.target.value;render();}if(event.target.id==='report-month'){reportMonth=event.target.value;render();}});
document.addEventListener('submit',event=>{
 if(event.target.id==='calendar-form'){
  event.preventDefault();
  try{
   const id=event.target.dataset.session,base=draftCalendar(state).find(s=>s.id===id)||{id,status:'Scheduled'};
   const candidate=readFields(event.target,base);editCalendarSession(state,candidate);calendarSelection=id;week=candidate.date<'2026-09-21'?0:1;
   notice='Draft calendar updated. The conflict list has been recalculated.';error='';render();
  }catch(err){error=err.message;render();}
  return;
 }
 if(event.target.id==='session-add-form'){
  event.preventDefault();pendingDraft=event.target.dataset.draft==='true';pendingSetup=readFields(event.target,{id:pendingDraft?`draft-add-${batch().issues.length+1}`:`setup-${state.schedule.length+1}`,status:'Scheduled'});pendingSetup.standing=new FormData(event.target).has('weekly');
  const problems=conflictsFor(state,pendingSetup);
  dialog('Preview session',`<p>Client · ${e(pendingSetup.client)}<br>Therapist · ${e(pendingSetup.therapist)}<br>${pendingSetup.date} · ${pendingSetup.time} · ${pendingSetup.minutes} min<br>${place(pendingSetup)}</p><p>${pendingSetup.standing?'Weekly on this weekday. First sample occurrence only.':'One sample occurrence.'}</p>${pendingDraft?'<p class="muted">This is a draft. Any conflicts stay visible and block batch commit.</p>':''}${problems.length?`<div class="manual-alert">${problems.map(e).join('<br>')}</div>`:''}`,pendingDraft?btn('Save to draft','save-setup','primary'):problems.length?'':btn('Save to sample calendar','save-setup','primary'));return;
 }
 if(event.target.id==='staff-form'){event.preventDefault();const f=new FormData(event.target);addStaff(state,f.get('name'),f.get('hours'));notice='Staff added to prototype Setup.';render();return;}
 if(event.target.id==='client-form'){event.preventDefault();addClient(state,new FormData(event.target).get('name'));notice='Client added to prototype Setup.';render();return;}
 if(event.target.id!=='leave-form')return;event.preventDefault();const form=new FormData(event.target);
 try{startBatch(state,scenario,{therapists:form.getAll('therapist'),start:form.get('start'),end:form.get('end')});selected=state.batch.issues[0]?.id;calendarSelection=null;go(state.batch.issues.length?'schedule':'review');}catch(err){error=err.message;render();}
});
document.addEventListener('click',event=>{
 const control=event.target.closest('[data-action]');if(!control)return;const action=control.dataset.action,value=control.dataset.value;
 try{
  if(['schedule','setup','reports','leave','review','preview','notifications'].includes(action)){go(action);return;}
  if(action==='calendar-conflicts'){calendarSelection=null;go('schedule');return;}
  if(action==='close'){$('#modal').close();return;}
  if(action==='reset'){dialog('Reset the walkthrough?','<p>This clears your prototype decisions and restores the original fictional schedule and 15 rooms. Existing application data is untouched.</p>',btn('Reset sample data','reset-confirm','primary'));return;}
  if(action==='reset-confirm'){state=initial();scenario='simple';week=0;go('schedule');return;}
  if(action==='week'){week=Number(value);render();return;}
  if(action==='calendar-select'){calendarSelection=value;const s=draftCalendar(state).find(s=>s.id===value);if(s)week=s.date<'2026-09-21'?0:1;error='';render();return;}
  if(action==='conflict-suggestions'){selected=value;calendarSelection=null;const s=draftCalendar(state).find(s=>s.id===value);if(s)week=s.date<'2026-09-21'?0:1;error='';render();showAlternatives(value);return;}
  if(action==='calendar-add'||action==='calendar-add-day'){addSessionDialog(action==='calendar-add-day'?value:'');return;}
  if(action==='calendar-cancel'){const s=draftCalendar(state).find(s=>s.id===value);dialog('Cancel this draft session?',`<p>${e(s.client)} · ${s.date} ${s.time}. This cancellation will remain in the draft until commit.</p>`,btn('Confirm cancellation','calendar-cancel-confirm','danger',value));return;}
  if(action==='calendar-cancel-confirm'){const s=draftCalendar(state).find(s=>s.id===value);editCalendarSession(state,{...s,status:'Cancelled'});notice='Session cancelled in the draft. Conflicts updated.';error='';render();return;}
  if(action==='details'){const s=state.schedule.find(s=>s.id===value);dialog(e(s.client),`<p>${s.date} · ${s.time} · ${s.minutes} minutes</p><p>${e(s.therapist)} · ${place(s)}</p><h3>Assigned therapists</h3><p>Major: Morgan Maple<br>Second: Taylor Maple<br>Third: Casey Maple</p><p class="muted">${s.location==='Home'?'The full booked duration includes any extra time entered by the admin. No room is reserved.':'Weekly standing commitment represented by a supplied dated occurrence.'}</p>`,btn('Report leave','leave','primary'));return;}
  if(action==='select'){selected=value;error='';render();return;}
  if(action==='alternative'){selected=value;showAlternatives(value);return;}
  if(action==='use-option'){const [id,index]=value.split(':');const candidate=workableOptions(state,id)[Number(index)];if(candidate.location==='Clinic')candidate.room=Number($(`#option-room-${index}`).value);delete candidate.rooms;saveManual(state,id,candidate);notice='Conflict-free option saved as a draft decision.';error='';render();return;}
  if(action==='manual'){calendarSelection=value||null;const target=draftCalendar(state).find(s=>s.id===value);if(target)week=target.date<'2026-09-21'?0:1;go('schedule');return;}
  if(action==='save-setup'){if(pendingDraft){editCalendarSession(state,pendingSetup);calendarSelection=pendingSetup.id;notice=`${pendingSetup.standing?'Weekly commitment':'Session'} saved to the draft. Conflicts have been recalculated.`;}else{addStanding(state,pendingSetup);notice=`${pendingSetup.standing?'Weekly commitment':'Session'} saved in prototype state. First occurrence appears in the calendar.`;}$('#modal').close();page='schedule';week=pendingSetup.date<'2026-09-21'?0:1;error='';render();return;}
  if(action==='invalid'){try{decide(state,value,'invalid');}catch(err){$('#modal').querySelector('p').textContent=err.message;}return;}
  if(action==='cancel'){dialog('Cancel this session?',`<p>${e(batch().issues.find(i=>i.id===value).original.client)} will have no session for this occurrence. This remains a draft decision until commit.</p>`,btn('Confirm cancellation','cancel-confirm','danger',value));return;}
  if(['accept','alternative-confirm','cancel-confirm'].includes(action)){decide(state,value,action==='accept'?'accept':action==='alternative-confirm'?'alternative':'cancel');notice='Draft decision saved. Review any remaining or reopened issues.';error='';render();return;}
  if(action==='reopen'){reopen(state,value);notice='Decision reopened. Dependent issues also need review.';render();return;}
  if(action==='abandon'){dialog('Abandon the whole batch?','<p>All draft decisions will be discarded. The committed sample schedule remains unchanged and no notifications are created.</p>',btn('Abandon batch','abandon-confirm','danger'));return;}
  if(['abandon-confirm','empty-close'].includes(action)){abandon(state);page='schedule';notice=state.notice;error='';render();return;}
  if(action==='commit'){if(unresolved(state))throw new Error(`${unresolved(state)} unresolved issues. Review them before committing.`);if(!$('#commit-check').checked)throw new Error('Confirm that you reviewed the decisions before committing.');try{commit(state);}catch(err){page='review';throw err;}page='notifications';notice=state.notice;error='';render();window.scrollTo(0,0);return;}
  if(action==='notify'){const task=state.notifications.find(t=>t.id===value);task.done=!task.done;render();return;}
  if(action==='add-room'){const room=state.nextRoom++;state.rooms.push(room);notice=`Room ${room} added to prototype inventory.`;error='';render();return;}
  if(action==='remove-room'){removeRoom(state,Number(value));notice=`Room ${value} removed from prototype inventory.`;error='';render();return;}
  if(action==='remove-staff'){removeStaff(state,value);notice='Staff removed from prototype Setup.';error='';render();return;}
  if(action==='remove-client'){removeClient(state,value);notice='Client removed from prototype Setup.';error='';render();return;}
  if(action==='save-hours'){setStaffHours(state,value,$(`[data-hours="${CSS.escape(value)}"]`).value);notice='Staff maximum hours saved in prototype Setup.';error='';render();return;}
  if(action==='print-report'){window.print();return;}
 }catch(err){error=err.message;notice='';render();window.scrollTo(0,0);}
});
render();








